--- #YAML:1.0
name:                Config-Std
version:             0.0.5
abstract:            Load and save configuration files in a standard format
license:             ~
author:              
    - Damian Conway <DCONWAY@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Std:                    0
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
